#! /usr/bin/env bash
# papis-short-help: Add the pdf as a student phdthesis

cp ~/.config/papis/templates/phdthesis.bib /tmp/phdthesis.bib
$READER $1 &
$EDITOR /tmp/phdthesis.bib
papis add $1 --from bibtex /tmp/phdthesis.bib --set tags NOTELESS --set project PROJECTLESS --no-open
papis doctor --checks key-type --fix NOTELESS
papis edit --notes NOTELESS
papis tag --remove NOTELESS --add TODO --add THESIS --add PROJECTLESS NOTELESS
