[opener]
pdff = [
    { run = 'zathura %s', desc = "Zathura", block = true, for = "unix" },
]

play = [
	{ run = 'mpv %s', orphan = true, for = "unix" },
]

edit = [
	{ run = 'nvim %s', block = true, for = "unix" },
]

display = [
    { run = 'sxiv %s', block = false, for = "unix" },
]

[open]
rules = [
    { mime = "application/pdf", use = [ "pdff", "reveal" ] },
    { mime = "video/*", use = "play" },
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "display" },
]
